server:
  port: 8888
spring:
  application:
    name: kanglong-eureka
eureka:
  client:
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    dollar-replacement: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000