server:
  port: 5800
  max-http-header-size: 102400
spring:
  application:
    name: search-service
  datasource:
    url: jdbc:mysql://localhost:3306/kanglong
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka