server:
  port: 8000
spring:
  application:
    name: business-service
  datasource:
    url: jdbc:mysql://localhost:3306/kanglong
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
    virtual-host: /
    template:
      exchange: itemdetail.direct
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka